# PyXRFPower: Main control window
# File: pyxrfpower_main_window.py
# Author: B. Roter

# This PyXRFPower window controls the input files and parameters used to display elemental images and calculate power spectral densities.

from PyQt6 import QtCore, QtGui, QtWidgets
from pyxrfpwr_math_fxns import round_correct as rc

class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super(QtWidgets.QMainWindow, self).__init__()
        MainWindow = self
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(916, 642)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 191, 16))
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 150, 121, 16))
        self.label_6.setObjectName("label_6")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 170, 571, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_2 = QtWidgets.QCheckBox(parent=self.layoutWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_2.addWidget(self.checkBox_2, 2, 1, 1, 1, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.checkBox = QtWidgets.QCheckBox(parent=self.layoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 1, 2, 1, 1, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_7 = QtWidgets.QLabel(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_8 = QtWidgets.QLabel(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_9 = QtWidgets.QLabel(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_10 = QtWidgets.QLabel(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.label_10.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.label_11.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(10, 360, 241, 16))
        self.label_14.setObjectName("label_14")
        self.checkBox_3 = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 380, 85, 20))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(10, 380, 85, 20))
        self.checkBox_4.setObjectName("checkBox_4")
        self.layoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(40, 410, 261, 54))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_16 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 1, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_15 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.spinBox = QtWidgets.QSpinBox(parent=self.layoutWidget_2)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_3.addWidget(self.spinBox, 0, 1, 1, 1)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(parent=self.layoutWidget_2)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_3.addWidget(self.doubleSpinBox, 1, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(10, 490, 201, 16))
        self.label_17.setObjectName("label_17")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 560, 181, 32))
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 761, 101))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.toolButton = QtWidgets.QToolButton(parent=self.layoutWidget1)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout.addWidget(self.toolButton, 0, 2, 1, 1, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.toolButton_2 = QtWidgets.QToolButton(parent=self.layoutWidget1)
        self.toolButton_2.setArrowType(QtCore.Qt.ArrowType.LeftArrow)
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout.addWidget(self.toolButton_2, 1, 2, 1, 1, QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.toolButton_3 = QtWidgets.QToolButton(parent=self.layoutWidget1)
        self.toolButton_3.setArrowType(QtCore.Qt.ArrowType.RightArrow)
        self.toolButton_3.setObjectName("toolButton_3")
        self.gridLayout.addWidget(self.toolButton_3, 1, 3, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.comboBox = QtWidgets.QComboBox(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(0, "")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout.addWidget(self.comboBox_2, 2, 1, 1, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 510, 351, 23))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_18 = QtWidgets.QLabel(parent=self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 0, 0, 1, 1)
        self.spinBox_2 = QtWidgets.QSpinBox(parent=self.layoutWidget2)
        self.spinBox_2.setMaximum(1000000)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_4.addWidget(self.spinBox_2, 0, 1, 1, 1)
        self.layoutWidget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 300, 211, 31))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_5.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_13 = QtWidgets.QLabel(parent=self.layoutWidget_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.checkBox_3 = QtWidgets.QCheckBox(parent=self.layoutWidget_3)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_5.addWidget(self.checkBox_3, 0, 1, 1, 2)
        self.label_12 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(10, 280, 211, 16))
        self.label_12.setObjectName("label_12")
        self.label_19 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(260, 0, 481, 31))
        self.label_19.setWordWrap(True)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(480, 570, 431, 41))
        self.label_20.setWordWrap(True)
        self.label_20.setObjectName("label_20")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 776, 24))
        self.menubar.setObjectName("menubar")
        self.menuView = QtWidgets.QMenu(parent=self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuResolution_Parameter_Summary = QtWidgets.QMenu(parent=self.menuView)
        self.menuResolution_Parameter_Summary.setObjectName("menuResolution_Parameter_Summary")
        MainWindow.setMenuBar(self.menubar)
        MainWindow.setStatusBar(self.statusbar)
        self.actionElemental_Images_2D_PSD_Plots = QtGui.QAction(parent=MainWindow)
        self.actionElemental_Images_2D_PSD_Plots.setObjectName("actionElemental_Images_2D_PSD_Plots")
        self.actionAzimuthal_PSD_Plot = QtGui.QAction(parent=MainWindow)
        self.actionAzimuthal_PSD_Plot.setObjectName("actionAzimuthal_PSD_Plot")
        self.actionCircular_X_ray_Beam = QtGui.QAction(parent=MainWindow)
        self.actionCircular_X_ray_Beam.setObjectName("actionCircular_X_ray_Beam")
        self.actionNon_Circular_X_ray_Beam = QtGui.QAction(parent=MainWindow)
        self.actionNon_Circular_X_ray_Beam.setObjectName("actionNon_Circular_X_ray_Beam")
        self.menuResolution_Parameter_Summary.addAction(self.actionCircular_X_ray_Beam)
        self.menuResolution_Parameter_Summary.addAction(self.actionNon_Circular_X_ray_Beam)
        self.menuView.addAction(self.actionElemental_Images_2D_PSD_Plots)
        self.menuView.addAction(self.actionAzimuthal_PSD_Plot)
        self.menuView.addAction(self.menuResolution_Parameter_Summary.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.checkBox.setDisabled(True)
        self.checkBox_2.setDisabled(True)
        self.checkBox_3.setDisabled(True)
        self.checkBox_4.setDisabled(True)
        self.comboBox.setDisabled(True)
        self.comboBox_2.setDisabled(True)
        self.doubleSpinBox.clear()
        self.doubleSpinBox.setDisabled(True)
        self.menuView.setDisabled(True)
        self.toolButton_2.setDisabled(True)
        self.toolButton_3.setDisabled(True)
        self.pushButton.setDisabled(True)
        self.spinBox.clear()
        self.spinBox.setDisabled(True)
        self.spinBox_2.clear()
        self.spinBox_2.setDisabled(True)

        self.show()

        self.times = "\u00D7"

    def update_file_info_startup(self, files, directory):
        self.comboBox.clear()
        self.comboBox.addItems(files)
        self.label_5.setText(str(directory))

    def further_initialization(self, sigma, alpha):
        self.checkBox_3.setDisabled(False)
        self.checkBox_3.setChecked(True)
        self.checkBox_4.setDisabled(False)
        self.checkBox_4.setChecked(True)
        self.comboBox.setDisabled(False)
        self.doubleSpinBox.setDisabled(False)
        self.doubleSpinBox.setValue(alpha)
        self.pushButton.setDisabled(False)
        self.spinBox.setDisabled(False)
        self.spinBox.setValue(sigma)
        self.spinBox_2.setDisabled(False)

    def reset_pixel_dims_checkbox(self):
        self.checkBox.setChecked(False)
        self.checkBox.setDisabled(False)

    def update_img_dims(self, nx, ny):
        self.label_10.setText(str(nx) + " " + self.times + " " + str(ny))

    def update_pixel_dims(self, dx, dy):
        self.label_11.setText(str(rc(dx, 2)) + " " + self.times + " " + str(rc(dy, 2)))

    def update_error_msg(self, msg = None):
        if msg is not None:
            self.label_19.setText(msg)
        
        else:
            self.label_19.clear()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyXRFPower"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700; text-decoration: underline;\">Directory and File Information</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700; text-decoration: underline;\">Image Information</span></p></body></html>"))
        self.checkBox_2.setText(_translate("MainWindow", "Enabled"))
        self.checkBox.setText(_translate("MainWindow", "Use different dimensions"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Image Dimensions (pixels × pixels):</p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Pixel Dimensions (&mu;m × &mu;m):</p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Padding:</p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700; text-decoration: underline;\">Gaussian Edge Smoothing (Optional)</span></p></body></html>"))
        self.checkBox_3.setText(_translate("MainWindow", "Enabled"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Roll-off Tuning Parameter:</p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "Standard Deviation (pixels):"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700; text-decoration: underline;\">Azimuthal Frequency Bin Selection</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Preview Elemental Image"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Current Directory:</p></body></html>"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Current File:</p></body></html>"))
        self.toolButton_2.setText(_translate("MainWindow", "..."))
        self.toolButton_3.setText(_translate("MainWindow", "..."))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Synchrotron:</p></body></html>"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Advanced Photon Source (APS)"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "National Synchrotron Light Source II (NSLS-II)"))
        self.label_18.setText(_translate("MainWindow", "Number of Azimuthal Frequency Bins:"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\">Circular X-ray Beam:</p></body></html>"))
        self.checkBox_4.setText(_translate("MainWindow", "Enabled"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:700; text-decoration: underline;\">Experimental Setup Information</span></p></body></html>"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:10pt;\">Developer: B. Roter, Applied Physics Ph.D. Candidate, Northwestern University (2024)</span></p><p align=\"right\"><span style=\" font-size:10pt;\">Email benjaminroter2026@u.northwestern.edu for any suggestions and/or bugs.</span></p></body></html>"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuResolution_Parameter_Summary.setTitle(_translate("MainWindow", "Resolution Parameter Summary"))
        self.actionElemental_Images_2D_PSD_Plots.setText(_translate("MainWindow", "Elemental Images/2D PSD Plots"))
        self.actionAzimuthal_PSD_Plot.setText(_translate("MainWindow", "Azimuthal PSD Plot"))
        self.actionCircular_X_ray_Beam.setText(_translate("MainWindow", "Circular X-ray Beam"))
        self.actionNon_Circular_X_ray_Beam.setText(_translate("MainWindow", "Non-Circular X-ray Beam"))